
TESTIMONIALS_DATA = [
    {
        "id": 1,
        "name": "Dr. Deep Jyoti Gurung",
        "title": "Assistant Professor",
        "organization": "DREAMS Head Faculty coordinator of CU | Certified Microsoft Innovative Educator",
        "content": "As the DREAMS program's faculty coordinator, I cannot express how transformative this experience has been for me. The program's emphasis on leadership, interpersonal, and personal development skills has assisted me in developing skills necessary for my role as a teacher and mentor. Being a part of this program has also provided me with an exceptional opportunity to positively impact the lives of school students. I've had the pleasure of watching students discover their strengths and develop essential skills that will help them succeed in all aspects of life through the DREAMS program. It allowed me to positively impact lives and community, while also expanding my collaboration network, research and publication opportunities. My goal for the DREAMS program is to broaden its reach and impact. The program has the potential to benefit even more students and communities worldwide, and I am excited to be a part of making that vision a reality. This program has taught me much about myself, my community, and the power of mentoring and leadership. Although there have been difficulties along the way, they have only reinforced my belief in the importance of this program and its ability to effect positive change in the world.",
        "image": "testimonial/Dr-Deep-Jyoti-Gurung.jpg",
        "date": "2021-07-12",
        "featured": True,
        "category": ""
    },
    {
        "id": 2,
        "name": "Jo Anto Nadamukath",
        "title": "",
        "organization": "",
        "content": "GYLN is one of the best things that happened to me this year. I started as a regular mentor in a small chapter of Dreams, from there I became the coordinator of Dreams media and finally to GYLN. In GYLN, we have people coming from different walks of life, countries, cultures, languages, and qualifications. At GYLN I have an opportunity to show my talents, learn about new experiences and cultures. At times the team identifies my problems and tries to give me a better solution. I am really happy and proud to be a member of GYLN. The only suggestion I have is to bring up more activities and participants in the coming future.",
        "image": "testimonial/user.png",
        "date": "2023-02-05",
        "featured": False,
        "category": ""
    },
    {
        "id": 3,
        "name": "Kaici G",
        "title": "",
        "organization": "",
        "content": "I love the platform and I feel the platform provides a lot of opportunities to talk and grow. I’m comfortable speaking during each meeting and your team made us comfortable to interact with the participants. I truly enjoy the experience. I think each meeting is always fun because we discuss different topics and it gives us chance to bring new perspectives to situations.",
        "image": "testimonial/user.png",
        "date": "2020-09-18",
        "featured": False,
        "category": ""
    },
    {
        "id": 4,
        "name": "Samuel",
        "title": "",
        "organization": "",
        "content": "As a whole, I think the GLYN platform is amazing. It gets young leaders to interact with one another on an international level. Can never have too much of that. It’s very great to have engaging discussions with each one of them.",
        "image": "testimonial/user.png",
        "date": "2022-11-09",
        "featured": False,
        "category": ""
    },
    {
        "id": 5,
        "name": "Canaan Charrior",
        "title": "",
        "organization": "",
        "content": "I’ve witnessed the program change lives in a way that I have never seen any program with similar goals could ever even imagine. Everyone should have a chance to see that they can do anything, and I will help in any way I can to make that happen.",
        "image": "testimonial/Janet.jpg",
        "date": "2019-12-03",
        "featured": True,
        "category": ""
    },
    {
        "id": 6,
        "name": "Robin Sehon",
        "title": "",
        "organization": "",
        "content": "Really innovative concept.. I was looking forward for such curated content and i got more than i was expecting. I am so far very thrilled with overall experience and improvement.",
        "image": "testimonial/Kaici-Gordon_2.jpeg",
        "date": "2024-03-22",
        "featured": False,
        "category": ""
    },
    {
        "id": 7,
        "name": "Hope LeNoir",
        "title": "",
        "organization": "",
        "content": "I was organizing my closet and came across my DREAMS tshirt. This reminded me of how much fun I had with your students and how your volunteer team made me feel extremely welcome. Thank you for allowing me to be a part of the DREAMS.",
        "image": "testimonial/Hope-Lenior.png",
        "date": "2021-01-14",
        "featured": False,
        "category": ""
    },
    {
        "id": 8,
        "name": "Mr. Jestin Joseph",
        "title": "",
        "organization": "DREAMS Changanacherry Chapter, Kerala | Executive Head, Dreams Research Wing",
        "content": "During my school days, I was often labeled as a weak student and struggled to express myself. This caused me to run away from challenges and opportunities that I felt were beyond my capabilities. However, everything changed when I joined the DREAMS program. The DREAMS program has been a game-changer for me, helping me to grow in ways I never thought possible. It has given me hope and enabled me to overcome my fears, allowing me to dream bigger and achieve more in my life. One of the most valuable aspects of the program has been the ample opportunities it provides. As a DREAMS participant, I have been a mentor, leader, coordinator, and trainer, all of which have been invaluable experiences in my personal and professional development. Through these roles, I have learned important skills such as communication, collaboration, and problem-solving, which have helped me succeed in the program and my career and personal life. Overall, the DREAMS program has been a transformative experience for me. It has helped me to develop into a more confident and capable individual, and given me the tools to pursue my dreams and achieve my goals. I am grateful for the opportunity to be a part of such an incredible program, and I would highly recommend it to anyone looking to grow and achieve their full potential.",
        "image": "testimonial/JestinJoseph.jpg",
        "date": "2022-06-29",
        "featured": False,
        "category": ""
    },
    {
        "id": 9,
        "name": "Anne Marie Ogden",
        "title": "",
        "organization": "Mentor, DREAMS",
        "content": "When I first came to the DREAMS, I thought it was just another summer camp. I didn’t quite understand the full concept of it, and most definitely I didn't realize the impact it would soon have not only on these kids but also on myself. Day one of my first summer program felt a little new to everyone, both to the students and to the mentors. Everyone was just getting to know one another, and even for me personally as an introvert, it was a little difficult at first to go out there and make small talk, but then I saw how some students were doing it with such ease. So they inspired me the very first day, before we even began lessons. Around the third day, it seemed as if they had been friends for quite a while. The formation of relationships between the students was such a beautiful thing to see. This program not only teaches students life values, but it also demonstrates how they can put these values into practice in their everyday lives. Normally we have all groups with a few students and two mentors, and we get to teach and pour into them how we learned these values over these years and the ways we succeeded in doing them, or how we felt and learned from it. Different speakers from the same town will come and talk about a particular value that day, and you can really see how the students relate to and listen to that person, especially because they mostly come from our own town. The very best part of teaching students these values is seeing them come back and tell you how they've used them, and even better, the parents will come back and talk about the transformation they’ve seen in their child.",
        "image": "testimonial/AnnemarieOgden.jpg",
        "date": "2020-08-15",
        "featured": False,
        "category": ""
    },
    {
        "id": 10,
        "name": "Ms. Jasmine Kaur Sahni",
        "title": "Chief Mentor",
        "organization": "DREAMS Bangalore Chapter",
        "content": "\"We make a living by what we get, but we make a life by what we give.\" - Winston Churchill If I must answer a question, why I joined Dreams, this quote explains my journey with Dreams perfectly. As we know, Dreams is an intergenerational program and inspiration comes in all shapes and sizes. If I mentor students younger than me, I am also gaining knowledge from these mentors. Throughout our lives, we are always taught to listen to our elders, because they have a wealth of knowledge and experience to share - which is True. But what often goes underappreciated is what we can learn from the younger generations around us as we get older. It could be how to appreciate new technologies, be more open minded and accepting, appreciating little moments or following your dreams, no matter what. Also, to reach any significant goal in life we need to overcome challenges along the way. But all of us working with Dreams consider ourselves \"A FAMILY\" and together we encounter each obstacle and press ourselves forward making DREAMS our \"HAPPY PLACE\"!!! I have been a part of Dreams for 3 years and all I want to say to anyone who is ready to volunteer as a Community Leader, is that it's the most wholesome experience as we are giving our time in this program as TIME IS CONSIDERED THE BIGGEST GIFT you can gift anyone and what can be better than the community we live in. So come let's join hands in this program and make a difference in the world we live in.",
        "image": "testimonial/user.png",
        "date": "2021-10-07",
        "featured": True,
        "category": ""
    },
    {
        "id": 11,
        "name": "Mr. Sebastian M T",
        "title": "Community Leader",
        "organization": "DREAMS Changanacherry Chapter, Kerala",
        "content": "I was introduced to DREAMS by Mr. James Anithottam, the then head of its affairs in Changanacherry in 2018. As a retired teacher, the idea of DREAMS fascinated me as I felt it was a solution to the imbalance between the slow learners and fast movers. Completion of school syllabus is time bound and teachers normally move on with the fast, intelligent students. This prevented the slow learners from gaining enough in their academic journey. Experiencing further, I realized that the scope of DREAMS is far reaching. It benefited not only the slow learners but all its stakeholders. The key is direct involvement and practice. You are into listening, reading, writing, speaking, dancing, acting, drawing, playing, emulating and whatever....., your best is brought out!. The DREAMS curriculum is unmatched. It aims at developing personal, social and leadership qualities in a short, 28 day program. It literally makes one grow gracefully to maturity, empowering self, acquiring values, mastering skills, making socially responsible, committed and trustworthy. I am happy and feel accomplished as I see our efforts make a huge difference in society. Parents very often express their gratitude for the positive changes in their children. Mentors, the middle rung DREAMS family, through their involvement grow strong, confident and well equipped to face their future. For me, it is also a platform to make friends and to give back to the Community from the bounty of blessings I received from it.",
        "image": "testimonial/Sebastian.jpg",
        "date": "2019-11-21",
        "featured": False,
        "category": ""
    },
    {
        "id": 12,
        "name": "Ms. Lisa",
        "title": "",
        "organization": "",
        "content": "First and foremost, I was impressed by the passion and vision with which DREAMS is now being implemented worldwide. In my opinion, the topics of empowerment, strengthening one's own resilience and dealing with one's own goals, desires and feelings are given far too little attention in our society. It's more about performance and less about the question of what talents/passions exist and how they can be lived out. DREAMS deals with all of this outside of the school and family context, so that the students can learn more freely, at their own pace, without pressure. One student said in the last workshop that DREAMS means joy to her. At that point it was clear to me that we, especially the students, had done everything right. The intensive and continuous support by the students, the trust in the group led to the fact that even difficult (biographical) topics could be discussed and endured together. The massive social and world-political conflicts and crises put a great strain on young people, but they are often alone with their worries and fears. The pressure to 'parry' and to fulfill the roles of student or son/daughter as inconspicuous as possible makes it difficult to address one's own needs with caregivers and teachers. DREAMS has helped students emerge empowered. For the future of DREAMS, I would like to see us bring the differences from the various countries and cultures closer together and see how we can profit from these different experiences.",
        "image": "testimonial/Lisa.jpg",
        "date": "2022-04-28",
        "featured": False,
        "category": ""
    },
    {
        "id": 13,
        "name": "Dr. Suzanne Mynette Mayo",
        "title": "",
        "organization": "FCS Lecture, Grambling State University",
        "content": "\"Never doubt that a small group of thoughtful, committed citizens can change the world; indeed its the only thing that ever has\" The Let Us Dream Conference has been one of the most inspiring experiences for the students I teach at Grambling State University (GSU) and for me since 2017. Dr. Glenda Island, Chair of the Department of Family and Consumer Sciences at GSU invited me to join her in 2018 for the conference at La Tech University in Ruston, LA as a part of the GSU our partnership with Christ University and Father Lijo, Founder of the conference. Since 2017 I have engaged students in the LUD conferences domestically and abroad into my classes as an example of teaching servant and transformational leadership, social responsibility and globalization. My most memorable single moment was in 202 during the Pandemic when the Student Panel was highlighted with student's comments and reflections on giving back to their communities and others in need. This panel awakened my inner core of what teaching and learning is all about and I continue to keep this spark today and into the future with this conference. Each time we begin to plan for the LUD Conferences in Louisiana each year, a natural disaster or worldwide or local crisis has occurred, but this has not put a damper on our ability to gather together, share insightful thoughts, research and practices and work to help us help others in the name of service to mankind. For the many persons who are Unsung Heroes, I salute Father Lijo and The Let Us Dream Conference is a master in featuring everyday great ones to give in the areas of health, education and social justice for all. I remain a LUD advocate and look forward to 2023 in India.",
        "image": "testimonial/SMT photo.png",
        "date": "2020-11-23",
        "featured": False,
        "category": ""
    },
    {
        "id": 14,
        "name": "Dr. Phinu Jose",
        "title": "",
        "organization": "",
        "content": "LUD Conference 2020 held completely Online from 20 November to 22 November was a life-changing experience indeed for me. While the Planning Committee began planning for the in-person Conference November 2020 as early as December 2019, when i was invited to join the team....no one in their wildest dreams thought Covid would turn our world upside down....and in many ways it was literally upside down....reverse mentoring by tech-savvy young volunteers in making the conference completely digital....venue didn't matter as all of us seemed to have lost sense of time and space......logging in to meetings early in the morning while the night seemed to never end at some places....as our universe started in the bedroom and ended in the kitchen during the terrible days of lockdown across the globe, LUD opened the screens into lives of people who joined us from SouthAfrica to Australia to New York to Zurich to Kerala and Bangalore....breaking barriers and building bridges across the boundaries defined by geography with only one philosophy...to make this world a better place! LUD Triennial Conference 2020 became the beacon of hope for all of us involved, so much so that we continued with the same spirit in organising the Annual Conference in 2021 and Local Conference in 2022 with the same zeal and enthusiasm. The success of these 3 years is not defined by the 40000+ registrations or views online but by the leaders nurtured through volunteerism and lives touched that make ordinary days seem extraordinarily blessed!",
        "image": "testimonial/Phinu Jose.jpg",
        "date": "2021-03-18",
        "featured": False,
        "category": ""
    },
    {
        "id": 15,
        "name": "Debbie Collett-O’Brien",
        "title": "",
        "organization": "Let Us Dream Liason - Binghamton University",
        "content": "In my role, I have worked with and helped coordinate the Let Us Dream Conference at Binghamton University since 2019 and have been amazed by the impact which this organization has had across the globe. The Let Us Dream Conferences has allowed practitioners, learners and community members come together, hone their skills in a variety of disciplines, and invigorate one another to bring out and strengthen sentiments of community, empathy and care which is already ingrained in the community itself. I love recruiting students, faculty members and staff at Binghamton University to get involved with the Let Us Dream Conferences as it provides an opportunity for international, interdisciplinary collaboration where you meet others who are passionate, innovative and driven to educate others about best-practices that will better the lives of others, while learning how to translate those skills in your own work. Let Us Dream has endless opportunities for involvement and working with Dean Laura Bronstein, Michael Kaufmann, Tracy Lyman and Jeff Smith has been such an amazing experience to see the wonderful work of those in the Binghamton community get recognized on a national- and global-level. It’s been such an honor to work with such accomplished, hardworking individuals who exemplify how to be a positive agent of change and empower others to do the same. I look forward to the continued partnership and collaboration between Binghamton University and Let Us Dream and how this work will positively change the local community in the years to come.",
        "image": "testimonial/CollettOBrien_Debbie2.jpg",
        "date": "2019-10-29",
        "featured": True,
        "category": ""
    },
    {
        "id": 16,
        "name": "Prof. Dr. Martin Klein",
        "title": "Vice President",
        "organization": "Catholic University of Applied Sciences NRW, Germany",
        "content": "60 years ago, on 18 August 1963, Martin Luther King gave his \"I have a dream\" speech at the Lincoln Memorial in Washington. It is one of the most famous speeches of the 20th century. The dream was to fight racial discrimination and to treat all citizens equal before the law. The dream of a better society is more relevant than ever. In the 21st century, too, there is hope of living in a society without discrimination and gender inequality. Hope, that companies take on social responsibility, produce sustainably and protect the environment. Unique about all these dreams is, that they will only be fulfilled, if we stand up for our convictions, act on them ourselves and convince others of our dreams. At the \"Let us Dream\"-conferences we dream together. The cooperation supported by visionary and committed people from all over the world is not only an important source of joy and inspiration. It is also a strong motivator for specific measures for implementation and helps enduring all the obstacles and setbacks along the way. Through the international exchange I was lucky to experience creativity and the power of imagination emerge across borders, so new ideas and innovations could be developed. The \"Let us Dream\"-conferences are supported by a community and live from the commitment and contributions of the volunteers. This is a gift and it would be great, if, at the end of the 21st century, the project was as well known as the speech mentioned in the beginning.",
        "image": "testimonial/Martin Klien.jpg",
        "date": "2022-08-11",
        "featured": False,
        "category": ""
    },
    {
        "id": 17,
        "name": "Rajesh P.I",
        "title": "Founder & Artistic Director",
        "organization": "The Actors Collective",
        "content": "My experience with the Dreams Professional Club has been tremendous. I have been associated with it right from the beginning. No matter what, I make it a point to attend all meetings. I must have missed it only a handful of times. I have found the meetings to be very useful. Since we are all people from different backgrounds, there is so much diversity and a wide array of perceptions here. The way each person approaches a challenge or an issue is vastly different, because each person's background, thought process, style of approach is so different and it gives everyone great learning opportunities. There is a lot of safety in this space and one can speak one's mind without worrying whether one is judged or not. When everyone is sharing their life experiences and not some arbitrary theory, the conversations get very interesting because they come from a space of great authenticity and vulnerability.",
        "image": "testimonial/RajeshPI.jpg",
        "date": "2020-05-07",
        "featured": False,
        "category": ""
    },
    {
        "id": 18,
        "name": "Colonel Ranjeev K Babu, VSM",
        "title": "Agile Trainer",
        "organization": "ICAgile Authorized Instructor",
        "content": "As a member of the DREAMS Professional Club, I have had the privilege of attending monthly meetings with individuals from diverse professional backgrounds, cultural orientations, and from across the globe. Despite geographical differences, we are united by a singular purpose of engaging in thought-provoking discussions. It has been fascinating to see how our diverse experiences and perspectives have enriched the conversations and contributed to our collective growth. The club has provided an excellent opportunity for cross-cultural exchange, and I have personally gained a lot from my esteemed fellow members. Overall, being part of the DREAMS Professional Club has been an enriching experience that has broadened my horizons and expanded my professional network and net-worth!",
        "image": "testimonial/ColRanjeevKBabu.jpg",
        "date": "2023-12-02",
        "featured": False,
        "category": ""
    },
    {
        "id": 19,
        "name": "Jotham B. Simon",
        "title": "GYLN Secretary",
        "organization": "Dallas, TX (USA)",
        "content": "My personal experience in the Global Youth Leadership Network has been nothing short of fantastic. It is such a privilege to be part of a worldwide movement that strives to empower young minds to be change-makers in this world. I have been able to cultivate new friendships, and explore interesting topics, all while having a safe space where I can express my thoughts and views without fear of being labeled as different. The GYLN promotes diversity and equity in our organization and welcomes all young leaders who qualify to join us on this journey. I have truly transformed into a better leader because of the GYLN because it fosters an environment in which one can truly thrive!",
        "image": "testimonial/user.png",
        "date": "2021-09-15",
        "featured": False,
        "category": ""
    },
    {
        "id": 20,
        "name": "Tirukovela Srikar",
        "title": "Mentor",
        "organization": "DREAMS Bangalore Chapter",
        "content": "My journey with DREAMS has paved the way for my Mastery, starting as a volunteer, progressing to a mentor, then a chapter coordinator, then an overall program coordinator, and now a part of the Global Youth Leadership Network (GYLN) as a national representative. The Success and fulfillment I have achieved in both personal and professional aspects of my life are a testament to my experiences in this organization. DREAMS has put me in touch with my skills and passion suitable for a career in psychology. Something that I would take away and would like to pass down to the next generations of the organization, in Rev. Father Lijo’s words: “We all have made sacrifices in our lives, and the time we invest in the organization is one such sacrifice that we choose to make. It is important to make them count.” We thrive on commitment and volunteerism.",
        "image": "testimonial/Srikar.jpg",
        "date": "2020-02-27",
        "featured": True,
        "category": ""
    },
    {
        "id": 21,
        "name": "Mr Michael Kaufmann",
        "title": "Director",
        "organization": "Sam and Myra Ross Institute Green Chimneys Children’s Services New York, United States Leader from Conversation Club",
        "content": "Isolated by COVID restrictions in 2021 and limited in social contacts, stressed at the state of the world - joining the DREAMS Conversation Club opened a whole new world of friends, colleagues and contacts. Be the topic love, colors, food or dreams, the opportunity to share ideas, feelings and thoughts with an international group of diverse and engaged people has been immensely enriching for me. Now after COVID - everyone has busy lives again, not all of us can be there every time- but when we ARE together, sparks fly, laughter happens and energy is shared via ZOOM from India, to Germany to the United States and all around the globe.",
        "image": "testimonial/MichaelKaufmann.png",
        "date": "2022-12-06",
        "featured": False,
        "category": ""
    },
    {
        "id": 22,
        "name": "Patsy A Hughey, Ed. D",
        "title": "",
        "organization": "Louisiana Tech University, Ruston, LA",
        "content": "I am excited to be a part of the DREAM Conversation Club. This experience allows a global group of professionals to discuss various cultural, societal, and political topics in a spirit of collaboration and respect for each other’s differences. \"I understand\" these are two of the most powerful words you can say, personally and professionally. Whether we believe in the power of our daily rituals or hold a world-shifting viewpoint, acknowledging and respecting the perspectives of others is the tool that fuels the depth, value, and meaning of our contribution to and relationships with them. We all have varying opinions and ideas, making monthly conversations more interesting. The most rewarding takeaway from being a member of the DREAM Conversation Club is that when we can use our lens as a point of relatability to support another in their viewpoint or to provide a unique perspective that may foster an expanded view for them.",
        "image": "testimonial/PatsyAHughey.jpg",
        "date": "2020-07-30",
        "featured": False,
        "category": ""
    },
    {
        "id": 23,
        "name": "Abhishikth George John",
        "title": "Music Coordinator/ Choir Director",
        "organization": "CHRIST (Deemed to be University) Central Campus",
        "content": "DREAMS Band is a group of budding musicians coming together for one vision and mission to empower the society and holistically grow others around using music as an effective tool. The band is a balance between a professional and a college band. The freedom to express and space to grow are the two most important factors I have personally experienced being a part of the band for the last 4 years. The band really has an impact on people as the songs the band performs and the performances are very life-centric. Each performance for me was reliving the success through struggles in life, or cherishing the past memories. One of the most memorable moments of my time with the band was my first day in the band. To have got selected as a keyboardist for the band was a huge surprise in my life and a turning point to an in depth exploration in the field of music. As soon as I entered the jam room I could see a few musicians I really looked up to and the space made me feel very comfortable and I felt belonged. I found a bunch of friends who later in life turned out to be a strong support system and family away from home. The vision and mission of the band is what attracted me. Coming from a family involved in ministry I grew up understanding the importance of bringing a change in the society using my passion for music. The Band has absolutely put me in the most uncomfortable situations to mold me to become a good leader and teacher. The functioning in the band really made me capable of multiple responsibilities which includes coordination and other soft skills very essential for working under any institution.",
        "image": "testimonial/AbhishikithGeorge.jpg",
        "date": "2021-05-19",
        "featured": False,
        "category": ""
    },
    {
        "id": 24,
        "name": "Mr. Ibin Rigia",
        "title": "",
        "organization": "Mental health advocate | Mental health professional | Music enthusiast | Musician",
        "content": "Being part of the dreams band for me was a journey of self-discovery and holistic growth. It didn't only help me improve my musical abilities, but it also helped me to enhance my other skills like teamwork, leadership, decision-making, and social skills. Being in the same room with hardworking and dedicated individuals had a positive impact on me, and i was fortunate to have been able to learn so much from all the band members who were part of dreams band over the years. The most wonderful thing about the dreams band is that they never look for the best musicians. They instead look for the most dedicated and focused ones who are looking to grow holistically and are passionate about the goal of the Let us dream project. This is what sets it apart from any other band out there.",
        "image": "testimonial/IbinRigia.jpeg",
        "date": "2023-04-02",
        "featured": False,
        "category": ""
    },
    {
        "id": 25,
        "name": "Jaden Elijah Johnson",
        "title": "Music Head / DREAMS Band",
        "organization": "CHRIST (Deemed to be University) Central Campus",
        "content": "The Dreams Band not alone performs for various events but gives a message to every heart of the youth today. The Dreams band creates a Will-to-do motivation to create, to imagine and to go beyond what you can do in people's hearts. The Dreams Band gives a platform to help one another grow, improve their skills, and share knowledge and thoughts with the team. It provides a beautiful platform to expose ideas and creativity in the group. The Dreams Band has helped me to put in more ideas and creativity in the Band. The Band has given me incredible exposure and experience through various events. There is always a takeaway to learn and to grow through the events conducted, and these improve my skills and knowledge.",
        "image": "testimonial/Jaden_Elijah_Johnson.jpg",
        "date": "2020-10-21",
        "featured": False,
        "category": ""
    },
    {
        "id": 26,
        "name": "KALIKA MATHUR",
        "title": "Organizational Head",
        "organization": "DREAMS Band | CHRIST (Deemed to be University) Central Campus",
        "content": "The DREAMS band is not just another band. It has a vision, a mission, towards which it strives hard. It is a part of a bigger, global space, which is inclined wholeheartedly to bring about a positive change in society, through a powerful tool, music. DREAMS Band, brings musicians from varied backgrounds together, to promote the message of global harmony, peace and personal development. Band performances primarily emphasize on touching souls, as the songs chosen, and composed, are based on inspiring and motivating lives. A cardinal feature of the band, which certainly sets it apart, is the concept of public interactions. Prior to every song, the team members interact with the audience based on their personal anecdotes, experiences and about the song, which makes it enriching for the audience, and fosters personal growth and skill enhancement. What attracted me most towards joining the DREAMS band was its distinctiveness, in terms of performances, its functioning, and the fact that members here, perform solely for their passion towards music, and their connection with the bigger vision of the band, and no other materialistic objectives. Without a doubt, the DREAMS band has already given so much more than I could ever imagine. It has given me the opportunity to nurture the leader in me, the platform for my musical skills, as well as the perfect place to build memories and hold on to a lifetime of experiences, that too, at such an early step of my college life. I have built an emotional connection with it, and I can actually point to one of my personal anecdotes, where young students, after the performance, came forward, and presented hand-made tokens of gratitude for each one of us, and expressed their dream of becoming a musician one day. This was very overwhelming and has impacted me deeply, and I am greatly looking forward to being part of the band, and giving it the best of my ability, and contributing to its growth and flourishing.",
        "image": "testimonial/KALIKA_MATHUR.jpg",
        "date": "2023-01-08",
        "featured": False,
        "category": ""
    },
    {
        "id": 27,
        "name": "Dr. Prakash G S",
        "title": "Associate Professor",
        "organization": "Mentor Let US DREAM Research Wing",
        "content": "DREAMS is a wonderful Afterschool intervention programme I have ever seen as it works on the idea of a sustainable and replicable model. It is nice to see young college students and community leaders coming forward for a larger social cause. I along with young researchers at DREAMS engaged ourselves with a couple of community-based research at DREAMS and I am sure findings would help the society. DREAMS is really a life-giving platform to all those who have otherwise never dared to emerge as a successful and well-groomed individual. I wish the spirit and dedication of youth energy at DREAMS must be preserved, developed, and nurtured. I am sure the research series will ensure greater credibility and scientific culture across all the wings of DREAM.",
        "image": "testimonial/PrakashGS.jpg",
        "date": "2021-06-17",
        "featured": False,
        "category": ""
    }
]
