from django.contrib import admin
from django.urls import path, include

from .views import *

urlpatterns = [
    path('', index, name='main'),
    path('locations/<str:loc>', locations, name='locations'),
    path('about-us', aboutUs, name='about-us'),
    path('media', media, name='media'),
    path('newsletter', newsletter, name='newsletter'),
    path('press-release/', pressRelease, name="press-release"),
    path('photo-gallery/', photoGallery, name="photo-gallery"),
    path('youtube-media/', youtubeMedia, name="youtube-media"),
    path('Conferences', aboutConference, name='Conferences'),
    path('annualConference', allConferences, name='annualConference'),
    path('trriennial-conference', triennialConference,
         name='trriennial-conference'),
    path('triennial-conference-2020', triennialConference2020,
         name='tc-2020'),
    path('conference-2023', conference2023,
         name='conference-2023'),
    path('yclpCourse', yclpCourse, name='yclp-course'),
    path('research', research, name='research'),
    path('publications', publications, name='publications'),
    path('christ-university-bangalore', bangalorechristuniversity,
         name='christ-university-bangalore'),
    path('binghamton-university-new-york', binghamtonUniversity,
         name='binghamton-university-new-york'),
    path('christ-university-thiruvananthapuram', cuT,
         name='christ-university-thiruvananthapuram'),
    path('jyoti-nivas-college-autonomous', jncaB,
         name='jyoti-nivas-college-autonomous'),
    path('louisiana-tech-university', louisianatechuniversity,
         name='louisiana-tech-university'),
    path('donboscocollege', donboscocollege, name='donboscocollege'),
    path('loyolacollegeConference', loyolacollegeConference, name='loyolacollegeConference'),
    path('stannescollege', stannescollege, name='stannescollege'),
    path('universityofLouisianaMonroe', universityofLouisianaMonroe,
         name='universityofLouisianaMonroe'),
    path('allsaintssollege', allsaintssollege, name='allsaintssollege'),
    path('gramblingstateuniversitylouisiana', gramblingstateuniversitylouisiana,
         name='grambling-state-university-louisiana'),
    path('louisianastateuniversityshreveport', louisianastateuniversityshreveport,
         name='louisiana-state-university-shreveport'),
    path('dreams/<str:drm>', dreams, name='dreams'),
    path('locations/<str:loc>', locations, name='locations'),
    path('registration_user', registration_user, name='registration_user'),
    path('calender', calender, name='calender'),
    path('downloadcsv', downloadcsv, name='downloadcsv'),
    path('downloadvoltcsv',downloadvoltcsv, name='downloadvoltcsv'),
    path('downloadpartcsv',downloadpartcsv, name='downloadpartcsv'),
    path('testimonials', testimonials, name='testimonials'), 
    path('announcement', announcement, name='announcement'), 
    path('llfp', llfp, name='llfp'), 


]
