# Generated by Django 4.0.4 on 2022-10-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50)),
                ('dreams', models.CharField(max_length=20)),
                ('dreamsOption', models.CharField(max_length=20)),
            ],
        ),
    ]
